// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA08z2lfJHwCDvLMf6wyw4AqrCOdfHbCSs',
    appId: '1:326923145018:web:dfad9ddcf38575ade38a03',
    messagingSenderId: '326923145018',
    projectId: 'eshop-22b4e',
    authDomain: 'eshop-22b4e.firebaseapp.com',
    storageBucket: 'eshop-22b4e.firebasestorage.app',
    measurementId: 'G-48M5PGLVT8',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-SDxUXocqI5oLRPL1u-Iad1hkBMZtkdI',
    appId: '1:326923145018:ios:3abd08d5e64a0eb8e38a03',
    messagingSenderId: '326923145018',
    projectId: 'eshop-22b4e',
    storageBucket: 'eshop-22b4e.firebasestorage.app',
    iosBundleId: 'com.anshul.eshop',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXrFpRZFoM-8J709TMbySjtiXnMDAlYxI',
    appId: '1:326923145018:android:d0240611eceaced2e38a03',
    messagingSenderId: '326923145018',
    projectId: 'eshop-22b4e',
    storageBucket: 'eshop-22b4e.firebasestorage.app',
  );

}